version: 0.0
os: Windows
files:
  - source: /home/templates/home.html
    destination: /D:\AUT\2021 S1\rnd\DataAnnotator
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      
    - location: scripts/start_server
      timeout: 300
      
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      

